// AUTO-GENERATED BY npm run generate:wrappers. DO NOT EDIT MANUALLY.
import * as React from "react";
import { createComponent } from "@lit/react";

import {
  CindorButton as CindorButtonElement,
  CindorButtonGroup as CindorButtonGroupElement,
  CindorSplitButton as CindorSplitButtonElement,
  CindorChip as CindorChipElement,
  CindorTag as CindorTagElement,
  CindorIconButton as CindorIconButtonElement,
  CindorCard as CindorCardElement,
  CindorCalendar as CindorCalendarElement,
  CindorEventCalendar as CindorEventCalendarElement,
  CindorDataGrid as CindorDataGridElement,
  CindorBadge as CindorBadgeElement,
  CindorDivider as CindorDividerElement,
  CindorProvider as CindorProviderElement,
  CindorSpinner as CindorSpinnerElement,
  CindorAlert as CindorAlertElement,
  CindorBanner as CindorBannerElement,
  CindorActivityFeed as CindorActivityFeedElement,
  CindorActivityItem as CindorActivityItemElement,
  CindorAutocomplete as CindorAutocompleteElement,
  CindorAvatar as CindorAvatarElement,
  CindorProgress as CindorProgressElement,
  CindorMeter as CindorMeterElement,
  CindorBreadcrumbs as CindorBreadcrumbsElement,
  CindorSkeleton as CindorSkeletonElement,
  CindorStepper as CindorStepperElement,
  CindorLink as CindorLinkElement,
  CindorFieldset as CindorFieldsetElement,
  CindorForm as CindorFormElement,
  CindorFormField as CindorFormFieldElement,
  CindorFormRow as CindorFormRowElement,
  CindorGrid as CindorGridElement,
  CindorHelperText as CindorHelperTextElement,
  CindorErrorText as CindorErrorTextElement,
  CindorRange as CindorRangeElement,
  CindorFileInput as CindorFileInputElement,
  CindorFieldArray as CindorFieldArrayElement,
  CindorFilterBuilder as CindorFilterBuilderElement,
  CindorPagination as CindorPaginationElement,
  CindorPageHeader as CindorPageHeaderElement,
  CindorPanelInspector as CindorPanelInspectorElement,
  CindorDataTable as CindorDataTableElement,
  CindorDataViewToolbar as CindorDataViewToolbarElement,
  CindorEmptyState as CindorEmptyStateElement,
  CindorEmptySearchResults as CindorEmptySearchResultsElement,
  CindorIcon as CindorIconElement,
  CindorCodeBlock as CindorCodeBlockElement,
  CindorCoachmarkTour as CindorCoachmarkTourElement,
  CindorCommandBar as CindorCommandBarElement,
  CindorCommandPalette as CindorCommandPaletteElement,
  CindorContextMenu as CindorContextMenuElement,
  CindorDatePicker as CindorDatePickerElement,
  CindorDateRangePicker as CindorDateRangePickerElement,
  CindorDateTimePicker as CindorDateTimePickerElement,
  CindorListbox as CindorListboxElement,
  CindorDescriptionItem as CindorDescriptionItemElement,
  CindorDescriptionList as CindorDescriptionListElement,
  CindorMenu as CindorMenuElement,
  CindorMenuItem as CindorMenuItemElement,
  CindorMultiSelect as CindorMultiSelectElement,
  CindorNotificationCenter as CindorNotificationCenterElement,
  CindorTagInput as CindorTagInputElement,
  CindorNumberInput as CindorNumberInputElement,
  CindorSearch as CindorSearchElement,
  CindorSplitter as CindorSplitterElement,
  CindorSplitterPanel as CindorSplitterPanelElement,
  CindorSegmentedControl as CindorSegmentedControlElement,
  CindorCombobox as CindorComboboxElement,
  CindorDateInput as CindorDateInputElement,
  CindorTimeInput as CindorTimeInputElement,
  CindorRatingInput as CindorRatingInputElement,
  CindorToast as CindorToastElement,
  CindorToastRegion as CindorToastRegionElement,
  CindorTooltip as CindorTooltipElement,
  CindorToolbar as CindorToolbarElement,
  CindorPopover as CindorPopoverElement,
  CindorDropdownMenu as CindorDropdownMenuElement,
  CindorDropzone as CindorDropzoneElement,
  CindorDrawer as CindorDrawerElement,
  CindorInput as CindorInputElement,
  CindorInlineEdit as CindorInlineEditElement,
  CindorLayout as CindorLayoutElement,
  CindorLayoutContent as CindorLayoutContentElement,
  CindorLayoutHeader as CindorLayoutHeaderElement,
  CindorEmailInput as CindorEmailInputElement,
  CindorPasswordInput as CindorPasswordInputElement,
  CindorOption as CindorOptionElement,
  CindorMenubar as CindorMenubarElement,
  CindorNavigationRail as CindorNavigationRailElement,
  CindorNavigationRailItem as CindorNavigationRailItemElement,
  CindorTelInput as CindorTelInputElement,
  CindorUrlInput as CindorUrlInputElement,
  CindorColorInput as CindorColorInputElement,
  CindorCheckbox as CindorCheckboxElement,
  CindorSelect as CindorSelectElement,
  CindorStack as CindorStackElement,
  CindorRadio as CindorRadioElement,
  CindorDialog as CindorDialogElement,
  CindorTextarea as CindorTextareaElement,
  CindorSwitch as CindorSwitchElement,
  CindorTabPanel as CindorTabPanelElement,
  CindorTabs as CindorTabsElement,
  CindorAccordion as CindorAccordionElement,
  CindorTreeItem as CindorTreeItemElement,
  CindorTreeView as CindorTreeViewElement,
  CindorStatCard as CindorStatCardElement,
  CindorTimeline as CindorTimelineElement,
  CindorTimelineItem as CindorTimelineItemElement,
  CindorTransferList as CindorTransferListElement,
  CindorSortableList as CindorSortableListElement,
  CindorVirtualList as CindorVirtualListElement,
  CindorJsonViewer as CindorJsonViewerElement,
  CindorMarkdownEditor as CindorMarkdownEditorElement,
  CindorKanbanBoard as CindorKanbanBoardElement,
  CindorWorkspaceSwitcher as CindorWorkspaceSwitcherElement,
  CindorSideNav as CindorSideNavElement,
  CindorSideNavItem as CindorSideNavItemElement,
} from "cindor-ui-core";
export { clearToasts, dismissToast, ensureToastRegion, showToast } from "cindor-ui-core";
import "cindor-ui-core/register";

export const CindorButton = createComponent({
  react: React,
  tagName: "cindor-button",
  elementClass: CindorButtonElement
});

export const CindorButtonGroup = createComponent({
  react: React,
  tagName: "cindor-button-group",
  elementClass: CindorButtonGroupElement
});

export const CindorSplitButton = createComponent({
  react: React,
  tagName: "cindor-split-button",
  elementClass: CindorSplitButtonElement,
  events: {
    onToggle: "toggle"
  }
});

export const CindorChip = createComponent({
  react: React,
  tagName: "cindor-chip",
  elementClass: CindorChipElement
});

export const CindorTag = createComponent({
  react: React,
  tagName: "cindor-tag",
  elementClass: CindorTagElement,
  events: {
    onRemove: "remove"
  }
});

export const CindorIconButton = createComponent({
  react: React,
  tagName: "cindor-icon-button",
  elementClass: CindorIconButtonElement
});

export const CindorCard = createComponent({
  react: React,
  tagName: "cindor-card",
  elementClass: CindorCardElement
});

export const CindorCalendar = createComponent({
  react: React,
  tagName: "cindor-calendar",
  elementClass: CindorCalendarElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const CindorEventCalendar = createComponent({
  react: React,
  tagName: "cindor-event-calendar",
  elementClass: CindorEventCalendarElement,
  events: {
    onInput: "input",
    onChange: "change",
    onEventSelect: "event-select"
  }
});

export const CindorDataGrid = createComponent({
  react: React,
  tagName: "cindor-data-grid",
  elementClass: CindorDataGridElement,
  events: {
    onActiveCellChange: "active-cell-change",
    onCellEdit: "cell-edit",
    onSortChange: "sort-change"
  }
});

export const CindorBadge = createComponent({
  react: React,
  tagName: "cindor-badge",
  elementClass: CindorBadgeElement
});

export const CindorDivider = createComponent({
  react: React,
  tagName: "cindor-divider",
  elementClass: CindorDividerElement
});

export const CindorProvider = createComponent({
  react: React,
  tagName: "cindor-provider",
  elementClass: CindorProviderElement
});

export const CindorSpinner = createComponent({
  react: React,
  tagName: "cindor-spinner",
  elementClass: CindorSpinnerElement
});

export const CindorAlert = createComponent({
  react: React,
  tagName: "cindor-alert",
  elementClass: CindorAlertElement
});

export const CindorBanner = createComponent({
  react: React,
  tagName: "cindor-banner",
  elementClass: CindorBannerElement,
  events: {
    onDismiss: "dismiss",
    onOpenChange: "open-change"
  }
});

export const CindorActivityFeed = createComponent({
  react: React,
  tagName: "cindor-activity-feed",
  elementClass: CindorActivityFeedElement
});

export const CindorActivityItem = createComponent({
  react: React,
  tagName: "cindor-activity-item",
  elementClass: CindorActivityItemElement
});

export const CindorAutocomplete = createComponent({
  react: React,
  tagName: "cindor-autocomplete",
  elementClass: CindorAutocompleteElement,
  events: {
    onChange: "change",
    onInput: "input",
    onSuggestionSelect: "suggestion-select"
  }
});

export const CindorAvatar = createComponent({
  react: React,
  tagName: "cindor-avatar",
  elementClass: CindorAvatarElement
});

export const CindorProgress = createComponent({
  react: React,
  tagName: "cindor-progress",
  elementClass: CindorProgressElement
});

export const CindorMeter = createComponent({
  react: React,
  tagName: "cindor-meter",
  elementClass: CindorMeterElement
});

export const CindorBreadcrumbs = createComponent({
  react: React,
  tagName: "cindor-breadcrumbs",
  elementClass: CindorBreadcrumbsElement
});

export const CindorSkeleton = createComponent({
  react: React,
  tagName: "cindor-skeleton",
  elementClass: CindorSkeletonElement
});

export const CindorStepper = createComponent({
  react: React,
  tagName: "cindor-stepper",
  elementClass: CindorStepperElement,
  events: {
    onChange: "change",
    onInput: "input"
  }
});

export const CindorLink = createComponent({
  react: React,
  tagName: "cindor-link",
  elementClass: CindorLinkElement
});

export const CindorFieldset = createComponent({
  react: React,
  tagName: "cindor-fieldset",
  elementClass: CindorFieldsetElement
});

export const CindorForm = createComponent({
  react: React,
  tagName: "cindor-form",
  elementClass: CindorFormElement,
  events: {
    onReset: "reset",
    onSubmit: "submit"
  }
});

export const CindorFormField = createComponent({
  react: React,
  tagName: "cindor-form-field",
  elementClass: CindorFormFieldElement
});

export const CindorFormRow = createComponent({
  react: React,
  tagName: "cindor-form-row",
  elementClass: CindorFormRowElement
});

export const CindorGrid = createComponent({
  react: React,
  tagName: "cindor-grid",
  elementClass: CindorGridElement
});

export const CindorHelperText = createComponent({
  react: React,
  tagName: "cindor-helper-text",
  elementClass: CindorHelperTextElement
});

export const CindorErrorText = createComponent({
  react: React,
  tagName: "cindor-error-text",
  elementClass: CindorErrorTextElement
});

export const CindorRange = createComponent({
  react: React,
  tagName: "cindor-range",
  elementClass: CindorRangeElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const CindorFileInput = createComponent({
  react: React,
  tagName: "cindor-file-input",
  elementClass: CindorFileInputElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const CindorFieldArray = createComponent({
  react: React,
  tagName: "cindor-field-array",
  elementClass: CindorFieldArrayElement,
  events: {
    onChange: "change",
    onInput: "input"
  }
});

export const CindorFilterBuilder = createComponent({
  react: React,
  tagName: "cindor-filter-builder",
  elementClass: CindorFilterBuilderElement,
  events: {
    onChange: "change",
    onInput: "input"
  }
});

export const CindorPagination = createComponent({
  react: React,
  tagName: "cindor-pagination",
  elementClass: CindorPaginationElement,
  events: {
    onChange: "change"
  }
});

export const CindorPageHeader = createComponent({
  react: React,
  tagName: "cindor-page-header",
  elementClass: CindorPageHeaderElement
});

export const CindorPanelInspector = createComponent({
  react: React,
  tagName: "cindor-panel-inspector",
  elementClass: CindorPanelInspectorElement
});

export const CindorDataTable = createComponent({
  react: React,
  tagName: "cindor-data-table",
  elementClass: CindorDataTableElement,
  events: {
    onCellEdit: "cell-edit",
    onPageChange: "page-change",
    onRowAction: "row-action",
    onRowExpand: "row-expand",
    onSearchChange: "search-change",
    onSortChange: "sort-change"
  }
});

export const CindorDataViewToolbar = createComponent({
  react: React,
  tagName: "cindor-data-view-toolbar",
  elementClass: CindorDataViewToolbarElement
});

export const CindorEmptyState = createComponent({
  react: React,
  tagName: "cindor-empty-state",
  elementClass: CindorEmptyStateElement
});

export const CindorEmptySearchResults = createComponent({
  react: React,
  tagName: "cindor-empty-search-results",
  elementClass: CindorEmptySearchResultsElement
});

export const CindorIcon = createComponent({
  react: React,
  tagName: "cindor-icon",
  elementClass: CindorIconElement
});

export const CindorCodeBlock = createComponent({
  react: React,
  tagName: "cindor-code-block",
  elementClass: CindorCodeBlockElement
});

export const CindorCoachmarkTour = createComponent({
  react: React,
  tagName: "cindor-coachmark-tour",
  elementClass: CindorCoachmarkTourElement,
  events: {
    onClose: "close",
    onComplete: "complete",
    onOpenChange: "open-change",
    onStepChange: "step-change"
  }
});

export const CindorCommandBar = createComponent({
  react: React,
  tagName: "cindor-command-bar",
  elementClass: CindorCommandBarElement
});

export const CindorCommandPalette = createComponent({
  react: React,
  tagName: "cindor-command-palette",
  elementClass: CindorCommandPaletteElement,
  events: {
    onCancel: "cancel",
    onChange: "change",
    onClose: "close",
    onCommandSelect: "command-select",
    onInput: "input"
  }
});

export const CindorContextMenu = createComponent({
  react: React,
  tagName: "cindor-context-menu",
  elementClass: CindorContextMenuElement,
  events: {
    onToggle: "toggle"
  }
});

export const CindorDatePicker = createComponent({
  react: React,
  tagName: "cindor-date-picker",
  elementClass: CindorDatePickerElement,
  events: {
    onChange: "change",
    onInput: "input",
    onToggle: "toggle"
  }
});

export const CindorDateRangePicker = createComponent({
  react: React,
  tagName: "cindor-date-range-picker",
  elementClass: CindorDateRangePickerElement,
  events: {
    onChange: "change",
    onInput: "input",
    onToggle: "toggle"
  }
});

export const CindorDateTimePicker = createComponent({
  react: React,
  tagName: "cindor-date-time-picker",
  elementClass: CindorDateTimePickerElement,
  events: {
    onChange: "change",
    onInput: "input"
  }
});

export const CindorListbox = createComponent({
  react: React,
  tagName: "cindor-listbox",
  elementClass: CindorListboxElement
});

export const CindorDescriptionItem = createComponent({
  react: React,
  tagName: "cindor-description-item",
  elementClass: CindorDescriptionItemElement
});

export const CindorDescriptionList = createComponent({
  react: React,
  tagName: "cindor-description-list",
  elementClass: CindorDescriptionListElement
});

export const CindorMenu = createComponent({
  react: React,
  tagName: "cindor-menu",
  elementClass: CindorMenuElement
});

export const CindorMenuItem = createComponent({
  react: React,
  tagName: "cindor-menu-item",
  elementClass: CindorMenuItemElement
});

export const CindorMultiSelect = createComponent({
  react: React,
  tagName: "cindor-multi-select",
  elementClass: CindorMultiSelectElement,
  events: {
    onChange: "change",
    onInput: "input"
  }
});

export const CindorNotificationCenter = createComponent({
  react: React,
  tagName: "cindor-notification-center",
  elementClass: CindorNotificationCenterElement
});

export const CindorTagInput = createComponent({
  react: React,
  tagName: "cindor-tag-input",
  elementClass: CindorTagInputElement,
  events: {
    onChange: "change",
    onInput: "input"
  }
});

export const CindorNumberInput = createComponent({
  react: React,
  tagName: "cindor-number-input",
  elementClass: CindorNumberInputElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const CindorSearch = createComponent({
  react: React,
  tagName: "cindor-search",
  elementClass: CindorSearchElement,
  events: {
    onChange: "change",
    onInput: "input"
  }
});

export const CindorSplitter = createComponent({
  react: React,
  tagName: "cindor-splitter",
  elementClass: CindorSplitterElement,
  events: {
    onPanelResize: "panel-resize"
  }
});

export const CindorSplitterPanel = createComponent({
  react: React,
  tagName: "cindor-splitter-panel",
  elementClass: CindorSplitterPanelElement
});

export const CindorSegmentedControl = createComponent({
  react: React,
  tagName: "cindor-segmented-control",
  elementClass: CindorSegmentedControlElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const CindorCombobox = createComponent({
  react: React,
  tagName: "cindor-combobox",
  elementClass: CindorComboboxElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const CindorDateInput = createComponent({
  react: React,
  tagName: "cindor-date-input",
  elementClass: CindorDateInputElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const CindorTimeInput = createComponent({
  react: React,
  tagName: "cindor-time-input",
  elementClass: CindorTimeInputElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const CindorRatingInput = createComponent({
  react: React,
  tagName: "cindor-rating-input",
  elementClass: CindorRatingInputElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const CindorToast = createComponent({
  react: React,
  tagName: "cindor-toast",
  elementClass: CindorToastElement,
  events: {
    onClose: "close"
  }
});

export const CindorToastRegion = createComponent({
  react: React,
  tagName: "cindor-toast-region",
  elementClass: CindorToastRegionElement,
  events: {
    onToastShow: "toast-show",
    onToastRemove: "toast-remove"
  }
});

export const CindorTooltip = createComponent({
  react: React,
  tagName: "cindor-tooltip",
  elementClass: CindorTooltipElement
});

export const CindorToolbar = createComponent({
  react: React,
  tagName: "cindor-toolbar",
  elementClass: CindorToolbarElement
});

export const CindorPopover = createComponent({
  react: React,
  tagName: "cindor-popover",
  elementClass: CindorPopoverElement,
  events: {
    onToggle: "toggle"
  }
});

export const CindorDropdownMenu = createComponent({
  react: React,
  tagName: "cindor-dropdown-menu",
  elementClass: CindorDropdownMenuElement,
  events: {
    onToggle: "toggle"
  }
});

export const CindorDropzone = createComponent({
  react: React,
  tagName: "cindor-dropzone",
  elementClass: CindorDropzoneElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const CindorDrawer = createComponent({
  react: React,
  tagName: "cindor-drawer",
  elementClass: CindorDrawerElement,
  events: {
    onClose: "close"
  }
});

export const CindorInput = createComponent({
  react: React,
  tagName: "cindor-input",
  elementClass: CindorInputElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const CindorInlineEdit = createComponent({
  react: React,
  tagName: "cindor-inline-edit",
  elementClass: CindorInlineEditElement,
  events: {
    onCancel: "cancel",
    onChange: "change",
    onInput: "input",
    onToggle: "toggle"
  }
});

export const CindorLayout = createComponent({
  react: React,
  tagName: "cindor-layout",
  elementClass: CindorLayoutElement
});

export const CindorLayoutContent = createComponent({
  react: React,
  tagName: "cindor-layout-content",
  elementClass: CindorLayoutContentElement
});

export const CindorLayoutHeader = createComponent({
  react: React,
  tagName: "cindor-layout-header",
  elementClass: CindorLayoutHeaderElement
});

export const CindorEmailInput = createComponent({
  react: React,
  tagName: "cindor-email-input",
  elementClass: CindorEmailInputElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const CindorPasswordInput = createComponent({
  react: React,
  tagName: "cindor-password-input",
  elementClass: CindorPasswordInputElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const CindorOption = createComponent({
  react: React,
  tagName: "cindor-option",
  elementClass: CindorOptionElement
});

export const CindorMenubar = createComponent({
  react: React,
  tagName: "cindor-menubar",
  elementClass: CindorMenubarElement
});

export const CindorNavigationRail = createComponent({
  react: React,
  tagName: "cindor-navigation-rail",
  elementClass: CindorNavigationRailElement
});

export const CindorNavigationRailItem = createComponent({
  react: React,
  tagName: "cindor-navigation-rail-item",
  elementClass: CindorNavigationRailItemElement
});

export const CindorTelInput = createComponent({
  react: React,
  tagName: "cindor-tel-input",
  elementClass: CindorTelInputElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const CindorUrlInput = createComponent({
  react: React,
  tagName: "cindor-url-input",
  elementClass: CindorUrlInputElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const CindorColorInput = createComponent({
  react: React,
  tagName: "cindor-color-input",
  elementClass: CindorColorInputElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const CindorCheckbox = createComponent({
  react: React,
  tagName: "cindor-checkbox",
  elementClass: CindorCheckboxElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const CindorSelect = createComponent({
  react: React,
  tagName: "cindor-select",
  elementClass: CindorSelectElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const CindorStack = createComponent({
  react: React,
  tagName: "cindor-stack",
  elementClass: CindorStackElement
});

export const CindorRadio = createComponent({
  react: React,
  tagName: "cindor-radio",
  elementClass: CindorRadioElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const CindorDialog = createComponent({
  react: React,
  tagName: "cindor-dialog",
  elementClass: CindorDialogElement,
  events: {
    onClose: "close",
    onCancel: "cancel"
  }
});

export const CindorTextarea = createComponent({
  react: React,
  tagName: "cindor-textarea",
  elementClass: CindorTextareaElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const CindorSwitch = createComponent({
  react: React,
  tagName: "cindor-switch",
  elementClass: CindorSwitchElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const CindorTabPanel = createComponent({
  react: React,
  tagName: "cindor-tab-panel",
  elementClass: CindorTabPanelElement
});

export const CindorTabs = createComponent({
  react: React,
  tagName: "cindor-tabs",
  elementClass: CindorTabsElement,
  events: {
    onChange: "change"
  }
});

export const CindorAccordion = createComponent({
  react: React,
  tagName: "cindor-accordion",
  elementClass: CindorAccordionElement,
  events: {
    onToggle: "toggle"
  }
});

export const CindorTreeItem = createComponent({
  react: React,
  tagName: "cindor-tree-item",
  elementClass: CindorTreeItemElement
});

export const CindorTreeView = createComponent({
  react: React,
  tagName: "cindor-tree-view",
  elementClass: CindorTreeViewElement,
  events: {
    onChange: "change",
    onInput: "input"
  }
});

export const CindorStatCard = createComponent({
  react: React,
  tagName: "cindor-stat-card",
  elementClass: CindorStatCardElement
});

export const CindorTimeline = createComponent({
  react: React,
  tagName: "cindor-timeline",
  elementClass: CindorTimelineElement
});

export const CindorTimelineItem = createComponent({
  react: React,
  tagName: "cindor-timeline-item",
  elementClass: CindorTimelineItemElement
});

export const CindorTransferList = createComponent({
  react: React,
  tagName: "cindor-transfer-list",
  elementClass: CindorTransferListElement,
  events: {
    onChange: "change",
    onInput: "input"
  }
});

export const CindorSortableList = createComponent({
  react: React,
  tagName: "cindor-sortable-list",
  elementClass: CindorSortableListElement,
  events: {
    onReorder: "reorder",
    onInput: "input",
    onChange: "change"
  }
});

export const CindorVirtualList = createComponent({
  react: React,
  tagName: "cindor-virtual-list",
  elementClass: CindorVirtualListElement,
  events: {
    onRangeChange: "range-change"
  }
});

export const CindorJsonViewer = createComponent({
  react: React,
  tagName: "cindor-json-viewer",
  elementClass: CindorJsonViewerElement
});

export const CindorMarkdownEditor = createComponent({
  react: React,
  tagName: "cindor-markdown-editor",
  elementClass: CindorMarkdownEditorElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const CindorKanbanBoard = createComponent({
  react: React,
  tagName: "cindor-kanban-board",
  elementClass: CindorKanbanBoardElement,
  events: {
    onSelect: "select",
    onCardAction: "card-action",
    onCardMove: "card-move"
  }
});

export const CindorWorkspaceSwitcher = createComponent({
  react: React,
  tagName: "cindor-workspace-switcher",
  elementClass: CindorWorkspaceSwitcherElement,
  events: {
    onToggle: "toggle",
    onSelect: "select",
    onInput: "input",
    onChange: "change"
  }
});

export const CindorSideNav = createComponent({
  react: React,
  tagName: "cindor-side-nav",
  elementClass: CindorSideNavElement
});

export const CindorSideNavItem = createComponent({
  react: React,
  tagName: "cindor-side-nav-item",
  elementClass: CindorSideNavItemElement
});
